nodebuster_regions_all: dict[str, list[str]] = {
    "Menu": [
        "Upgrade Tree",
    ],
    "Upgrade Tree": [
        "Damage1Root",
        "Boss Drops",
    ],
    # Bit Regions
    "Damage1Root": [
        "Potency",
        "Pulse Bolts",
        "Skilled Salvager",
        "Sapper",
        "Scaling Regeneration",
        "Anti-Purple",
        "Blood Armor",
        "Auto-Collect",
        "Crypto Mine",
        "Milestones",
        "Spawn Exploders",
        "Net Armor",
        "Transplant",
        "Overloaded",
    ],
    # Node Regions
    "Potency": [
        "Big Crit",
        "Netblade",
        "Auto Pulser",
    ],
    "Pulse Bolts": ["Bolt Lethality"],
    "Skilled Salvager": [],
    "Sapper": [],
    "Scaling Regeneration": ["Drainer"],
    "Anti-Purple": [],
    "Blood Armor": ["Blood Visage"],
    "Auto-Collect": [],
    "Crypto Mine": [
        "Processor Acquisition",
        "Crypto Levels",
    ],
    "Milestones": [
        "Red Milestones",
        "Blue Milestones",
        "Yellow Milestones",
    ],
    "Spawn Exploders": [],
    # Node Regions off of netcoin
    "Thundering": [],
    "Pulser Pursuit": [],
    "Pulse Thumper": [],
    "Unending Parasite": ["Parasite Evolution"],
    "Parasite Evolution": ["Indomitable", "Insatiable"],
    "Insatiable": [],
    "Indomitable": ["Beyond"],
    "Beyond": ["Infinity"],


    # Netcoin Regions
    "Bolt Lethality": [],
    "Drainer": [],
    "Blood Visage": [],
    "Processor Acquisition": [],
    "Auto Pulser": ["Pulser Pursuit", "Pulse Thumper"],
    "Netblade": ["Thundering"],
    "Big Crit": [],
    "Overloaded": [],
    # Netcoin Regions off of main.
    "Transplant": ["Unending Parasite"],
    "Net Armor": [],
    # Battle
    "Boss Drops": ["Prestige 0"],
    "Prestige 0": ["Prestige 1"],
    "Prestige 1": ["Prestige 2"],
    "Prestige 2": ["Prestige 3"],
    "Prestige 3": ["Prestige 4"],
    "Prestige 4": ["Prestige 5"],
    "Prestige 5": ["Prestige 6"],
    "Prestige 6": ["Prestige 7"],
    "Prestige 7": ["Prestige 8"],
    "Prestige 8": ["Prestige 9"],
    "Prestige 9": ["Prestige 10"],
    "Prestige 10": ["Prestige 11"],
    "Prestige 11": ["Prestige 12"],
    "Prestige 12": ["Prestige 13"],
    "Prestige 13": ["Prestige 14"],
    "Prestige 14": ["Prestige 15"],
    "Prestige 15": ["Prestige 16"],
    "Prestige 16": ["Prestige 17"],
    "Prestige 17": ["Prestige 18"],
    "Prestige 18": ["Prestige 19"],
    "Prestige 19": ["Prestige 20"],
    "Prestige 20": ["Prestige 21"],
    "Prestige 21": ["Prestige 22"],
    "Prestige 22": ["Prestige 23"],
    "Prestige 23": ["Prestige 24"],
    "Prestige 24": ["Prestige 25"],
    "Prestige 25": [],
    # Milestone Regions
    "Red Milestones": [],
    "Blue Milestones": [],
    "Yellow Milestones": [],
    # Cryto Regions
    "Crypto Levels": [],
    "Infinity": ["Epilogue"],
    "Epilogue": [],
}
