nodebuster_regions_all: dict[str, list[str]] = {
    "Menu": [
        "Upgrade Tree",
    ],
    "Upgrade Tree": [
        "Damage1Root",
        "Milestone Page",
        "Boss Drops",
    ],
    # Bit Regions
    "Damage1Root": [
        "Endurance",
        "Connection Buster",
        "Crowding",
    ],
    "Endurance": ["Firewall", "Repair Tool",],
    "Crowding": [
        "Swarming",
        "Bit Boost",
        "Influence",
    ],
    "Firewall": ["Antivirus", "Boss Guard"],
    "Influence": ["Magnet"],
    "Boss Guard": ["Better Endurance"],
    "Repair Tool": ["Salvaging",],
    "Salvaging": [
        "Better Endurance",
        "Sapper",
        "Skilled Salvager",
    ],
    "Connection Buster": ["Giant Slayer",],
    "Giant Slayer": ["Colossus Slayer", "Repeating"],
    "Repeating": ["Proficiency", "Repeat-Repeating"],
    "Bit Boost": ["Node Finder", "Plundering"],
    "Plundering": [],
    "Proficiency": ["Potency"],
    "Magnet": [],
    "Repeat-Repeating": ["Pulse Bolts"],
    "Swarming": ["Infesting"],
    "Better Endurance": ["Big Heart", "Self-Repair"],
    "Big Heart": ["Transplant"],
    "Self-Repair": ["Scaling Regeneration"],
    "Antivirus": ["Bolster", "Swarm Defense System"],
    "Swarm Defense System": [],
    "Bolster": ["Super Armor"],
    # Node Regions
    "Potency": [
        "First Strike",
        "Nodeblade",
        "Crit Chance",
    ],
    "First Strike": ["Last Strike", "Ambush"],
    "Last Strike": ["Finishing Blow"],
    "Nodeblade": [
        "Auto Pulser",
        "Netblade",
    ],
    "Crit Chance": ["Crit Damage"],
    "Crit Damage": ["Big Crit"],
    "Ambush": [],
    "Finishing Blow": [],
    "Pulse Bolts": ["Bolt Damage", "Bolt Count"],
    "Bolt Damage": ["Bolt Burst"],
    "Bolt Count": ["Bolt Barrage"],
    "Bolt Burst": ["Bolt Lethality"],
    "Bolt Barrage": ["Bolt Lethality"],
    "Skilled Salvager": [],
    "Sapper": ["Patcher"],
    "Patcher": [],
    "Scaling Regeneration": ["Drainer"],
    "Infesting": ["Domain Expansion", "Overloaded"],
    "Domain Expansion": ["Crypto Mine", "B.I.G."],
    "Super Armor": ["Anti-Purple", "Bit Armor"],
    "Anti-Purple": [],
    "Bit Armor": ["Byte Armor"],
    "Byte Armor": [
        "Net Armor",
        "Focus Armor",
        "Blood Armor",
    ],
    "Blood Armor": ["Blood Visage"],
    "Colossus Slayer": [],
    "B.I.G.": ["Auto-Collect"],
    "Auto-Collect": [],
    "Crypto Mine": [
        "Processor Acquisition",
        "Crypto Levels",
    ],
    "Node Finder": [
        "Node Boost",
        "Milestones",
        "Spawn Exploders",
    ],
    "Milestones": [],
    "Node Boost": [],
    "Spawn Exploders": [],
    "Focus Armor": [],
    # Node Regions off of netcoin
    "Thundering": [],
    "Pulser Pursuit": [],
    "Pulse Thumper": [],
    "Unending Parasite": ["Parasite Evolution"],
    "Parasite Evolution": ["Indomitable", "Insatiable"],
    "Insatiable": [],
    "Indomitable": ["Beyond"],
    "Beyond" : ["Infinity"],
    # Netcoin Regions
    "Bolt Lethality": [],
    "Drainer": [],
    "Blood Visage": [],
    "Processor Acquisition": [],
    "Auto Pulser": ["Pulser Pursuit", "Pulse Thumper"],
    "Netblade": ["Bloodblade", "Thundering"],
    "Bloodblade": [],
    "Big Crit": [],
    "Overloaded": [],
    # Netcoin Regions off of main.
    "Transplant": ["Blood Injection"],
    "Blood Injection": ["Instant Repair", "Unending Parasite"],
    "Instant Repair": [],
    "Net Armor": [],
    # Battle
    "Boss Drops": ["Prestige 0"],
    "Prestige 0": ["Prestige 1"],
    "Prestige 1": ["Prestige 2"],
    "Prestige 2": ["Prestige 3"],
    "Prestige 3": ["Prestige 4"],
    "Prestige 4": ["Prestige 5"],
    "Prestige 5": ["Prestige 6"],
    "Prestige 6": ["Prestige 7"],
    "Prestige 7": ["Prestige 8"],
    "Prestige 8": ["Prestige 9"],
    "Prestige 9": ["Prestige 10"],
    "Prestige 10": ["Prestige 11"],
    "Prestige 11": ["Prestige 12"],
    "Prestige 12": ["Prestige 13"],
    "Prestige 13": ["Prestige 14"],
    "Prestige 14": ["Prestige 15"],
    "Prestige 15": ["Prestige 16"],
    "Prestige 16": ["Prestige 17"],
    "Prestige 17": ["Prestige 18"],
    "Prestige 18": ["Prestige 19"],
    "Prestige 19": ["Prestige 20"],
    "Prestige 20": ["Prestige 21"],
    "Prestige 21": ["Prestige 22"],
    "Prestige 22": ["Prestige 23"],
    "Prestige 23": ["Prestige 24"],
    "Prestige 24": ["Prestige 25"],
    "Prestige 25": [],
    # Milestone Regions
    "Milestone Page": [
        "Red Milestones",
        "Blue Milestones",
        "Yellow Milestones",
    ],
    "Red Milestones": [],
    "Blue Milestones": [],
    "Yellow Milestones": [],
    # Cryto Regions
    "Crypto Levels": [],
    "Infinity": ["Epilogue"],
    "Epilogue": [],
}
